### ISSUE TITLE
Build On Save

### ISSUE THREAD

**Issue by Abraxas-Knister** [latex-lsp/texlab#502]
I've found this https://gitanswer.com/build-on-save-not-working-in-version-3-0-0-897906002

and I'm experiencing that setting `"texlab.build.onSave" = true` in `kak-lsp` doesn't cause an automatic build.
Is build on save deprecated and might it be reintroduced?

**Comment by Abraxas-Knister** [comment]
docs/options.md still lists "texlab.build.onSave", that's why I tried it.

**Comment by pfoerster** [comment]
Thanks for the report. The setting `texlab.build.onSave` is already reintroduced (see the [Changelog](https://github.com/latex-lsp/texlab/blob/master/CHANGELOG.md#320---12062021) for more information). Can you share your full `texlab` config and a log file (`texlab -vvvv --log-file /some/path/texlab.log`) please to help diagnose the issue?

**Comment by Abraxas-Knister** [comment]
I'm using texlab in kakoune via the kak-lsp plugin.

I added the keys 
```
[language.latex]
filetypes = ["latex"]
roots = [".tex",".git", ".hg"]
command = "texlab"
settings_section = "texlab"
[language.latex.settings.texlab]
"texlab.build.executable" = "latexmk"
"texlab.build.args" = ["-pdf", "-interaction=nonstopmode", "-synctex=1", "%f"]
"texlab.build.onSave" = true
"texlab.chktex.onOpenAndSave" = true
"texlab.chktex.onEdit" = true
```
to the config file `~/.config/kak-lsp/kak-lsp.toml` and added the necessary config to enable LSP features and linting from texlab to the config for kakoune. As that might very well be a kak-lsp only issue I understand if this is closing or I am redirected.

As I'm starting texlab by means of kak-lsp, kak-lsp is responsible for logging and produced a log [like that](https://pastebin.com/8AKhWifg) on an example file 
```
\documentclass{scrartcl}
\begin{document}
    \def\x{\relax}
    \dfkj
\end{document}
```
where an empty line is added before the erroneous macro before saving. On startup, latexmk output files already existed.

**Comment by Abraxas-Knister** [comment]
[that's just the log](https://pastebin.com/AFMANaEZ) of the texlab server

**Comment by pfoerster** [comment]
Thanks for the logs. I think that `texlab` cannot deserialize the configuration response of `kak-lsp` correctly. For example, instead of `[{"texlab.build.onSave": true}]`, it expects `[{"build": {"onSave": true}}]`.
It should work if you change your `kak-lsp` configuration:

```toml
[language.latex]
filetypes = ["latex"]
roots = [".tex",".git", ".hg"]
command = "texlab"
settings_section = "texlab"

[language.latex.settings.texlab.build]
"executable" = "latexmk"
"args" = ["-pdf", "-interaction=nonstopmode", "-synctex=1", "%f"]
"onSave" = true

[language.latex.settings.texlab.chktex]
"onOpenAndSave" = true
"onEdit" = true
```
